version: "3.9"

services:
  craftscript-client:
    build:
      context: ../../
      dockerfile: .docker/development/Dockerfile
    image: craftscript-client
    ports:
      - "3000:80"
    environment:
      NODE_ENV: development
