name: Build DEV - Frontend

on:
  push:
    branches:
      - "___develop"
    paths-ignore:
      - "README.md"

  workflow_dispatch:

env:
  REACT_APP_BACKEND_URL: "https://api.craftscript.com/"

permissions:
  id-token: write
  contents: read

jobs:
  build-frontend-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start SSH agent and add private key
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.REMOTE_KEY }}" | ssh-add -
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth_sock

      - name: Start SSH agent and add private key
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.REMOTE_KEY }}" | ssh-add -
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth_sock

      - name: Deploy using rsync
        run: |
          rsync -avzr --delete -e "ssh -o StrictHostKeyChecking=no -i /root/.ssh" \
            /home/admin/web/craftscript.com/public_html/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}